// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JiHQFuCr3-4vwuIQixhdRvPhwRFSt-Y',
    appId: '1:1079440489094:web:51bf8437bda41b3dfa6f07',
    messagingSenderId: '1079440489094',
    projectId: 'onlineorder-demo',
    authDomain: 'onlineorder-demo.firebaseapp.com',
    storageBucket: 'onlineorder-demo.appspot.com',
    measurementId: 'G-NV43BBQGJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoONDqRYGnvJ50Lx5LyFXUuMt5E5FZzBg',
    appId: '1:1079440489094:android:013a9db258f4aaf5fa6f07',
    messagingSenderId: '1079440489094',
    projectId: 'onlineorder-demo',
    storageBucket: 'onlineorder-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvQzNx1-ODxGVieUdZ3QZ0YzwpKnnKLk',
    appId: '1:1079440489094:ios:88eba87221102fc9fa6f07',
    messagingSenderId: '1079440489094',
    projectId: 'onlineorder-demo',
    storageBucket: 'onlineorder-demo.appspot.com',
    iosBundleId: 'com.orderit.onlineOrderWebsiteApp',
  );
}
